const PAYMENTS_DATA = [
  {
    id: 'PAY-001',
    bookingId: 'BKG-001',
    serviceName: 'Full Home Deep Cleaning',
    provider: 'Sparkle Clean Pro',
    amount: 2499,
    paymentMethod: 'Credit Card',
    transactionId: 'TXN8A3F9E2B1C',
    date: '2026-07-16T10:30:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-002',
    bookingId: 'BKG-002',
    serviceName: 'AC Repair & Service',
    provider: 'CoolAir Experts',
    amount: 399,
    paymentMethod: 'UPI',
    transactionId: 'TXN7D2G4H5J6K',
    date: '2026-07-15T14:00:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-003',
    bookingId: 'BKG-003',
    serviceName: 'Bathroom Deep Clean',
    provider: 'CleanHome Services',
    amount: 799,
    paymentMethod: 'Debit Card',
    transactionId: 'TXN9L1M3N7P8Q',
    date: '2026-07-14T11:00:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-004',
    bookingId: 'BKG-004',
    serviceName: 'Kitchen Plumbing Fix',
    provider: 'FixIt Plumbing Co.',
    amount: 549,
    paymentMethod: 'Net Banking',
    transactionId: 'TXN2R5T8U0V9W',
    date: '2026-07-13T09:00:00Z',
    status: 'pending',
  },
  {
    id: 'PAY-005',
    bookingId: 'BKG-005',
    serviceName: 'Interior Wall Painting',
    provider: 'ColorCoat Pro',
    amount: 8999,
    paymentMethod: 'Credit Card',
    transactionId: 'TXN4X7Y1Z3A2B',
    date: '2026-07-12T16:00:00Z',
    status: 'refunded',
  },
  {
    id: 'PAY-006',
    bookingId: 'BKG-006',
    serviceName: 'Electrical Wiring Repair',
    provider: 'Shakti Electricals',
    amount: 349,
    paymentMethod: 'UPI',
    transactionId: 'TXN5C8D0E6F4G',
    date: '2026-07-11T15:30:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-007',
    bookingId: 'BKG-007',
    serviceName: 'Home Moving & Packing',
    provider: 'SmoothMove Packers',
    amount: 12999,
    paymentMethod: 'Net Banking',
    transactionId: 'TXN1H3J5K7L9M',
    date: '2026-07-10T08:00:00Z',
    status: 'failed',
  },
  {
    id: 'PAY-008',
    bookingId: 'BKG-008',
    serviceName: 'Facial & Spa Treatment',
    provider: 'Glow & Grace Spa',
    amount: 999,
    paymentMethod: 'Debit Card',
    transactionId: 'TXN6N8P0Q2R4S',
    date: '2026-07-09T12:00:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-009',
    bookingId: 'BKG-009',
    serviceName: 'Office Deep Cleaning',
    provider: 'Sparkle Clean Pro',
    amount: 4999,
    paymentMethod: 'Credit Card',
    transactionId: 'TXN3T5U7V9W1X',
    date: '2026-07-08T10:00:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-010',
    bookingId: 'BKG-010',
    serviceName: 'Smart Light Installation',
    provider: 'Shakti Electricals',
    amount: 1499,
    paymentMethod: 'UPI',
    transactionId: 'TXN8Y0Z2A4B6C',
    date: '2026-06-28T14:00:00Z',
    status: 'completed',
  },
  {
    id: 'PAY-011',
    bookingId: 'BKG-011',
    serviceName: 'Full Home Deep Cleaning',
    provider: 'EcoClean Solutions',
    amount: 3499,
    paymentMethod: 'Net Banking',
    transactionId: 'TXN9D1E3F5G7H',
    date: '2026-06-25T11:00:00Z',
    status: 'refunded',
  },
  {
    id: 'PAY-012',
    bookingId: 'BKG-012',
    serviceName: 'AC Gas Refill',
    provider: 'CoolAir Experts',
    amount: 1599,
    paymentMethod: 'Debit Card',
    transactionId: 'TXN2I4J6K8L0M',
    date: '2026-07-13T16:00:00Z',
    status: 'pending',
  },
]

export const INVOICES_DATA = PAYMENTS_DATA.filter(
  (p) => p.status === 'completed' || p.status === 'refunded'
).map((payment) => ({
  ...payment,
  invoiceNumber: `INV-${payment.bookingId}`,
  customerName: 'Rahul Sharma',
  customerEmail: 'rahul.sharma@email.com',
  customerAddress: '42, Greenfield Apartments, Andheri West, Mumbai - 400053',
  gst: 'GST-27AABCU9603B1Z2',
  subtotal: payment.amount,
  tax: Math.round(payment.amount * 0.18),
  total: payment.amount + Math.round(payment.amount * 0.18),
}))

export default PAYMENTS_DATA
