const NOTIFICATIONS_DATA = [
  {
    id: 'NOT-001',
    title: 'Booking Confirmed',
    message: 'Your Full Home Deep Cleaning with Sparkle Clean Pro is confirmed for tomorrow at 10:00 AM.',
    category: 'bookings',
    type: 'success',
    read: false,
    createdAt: '2026-07-16T08:30:00Z',
  },
  {
    id: 'NOT-002',
    title: 'Payment Successful',
    message: 'Payment of ₹2,499 for Home Deep Cleaning was successful. Thank you for your booking.',
    category: 'payments',
    type: 'success',
    read: false,
    createdAt: '2026-07-16T08:25:00Z',
  },
  {
    id: 'NOT-003',
    title: 'Special Offer Just for You',
    message: 'Get 25% off on AC Repair & Service this weekend. Use code: COOL25. Valid till Sunday.',
    category: 'offers',
    type: 'promo',
    read: false,
    createdAt: '2026-07-16T06:00:00Z',
  },
  {
    id: 'NOT-004',
    title: 'Provider On The Way',
    message: 'Your AC Repair technician from CoolAir Experts is on the way. Estimated arrival: 15 minutes.',
    category: 'bookings',
    type: 'info',
    read: true,
    createdAt: '2026-07-15T14:45:00Z',
  },
  {
    id: 'NOT-005',
    title: 'Review Reminder',
    message: 'How was your AC Repair service? Share your experience and help others make the right choice.',
    category: 'system',
    type: 'info',
    read: true,
    createdAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'NOT-006',
    title: 'New Message from Provider',
    message: 'Sparkle Clean Pro sent you a message regarding your upcoming cleaning appointment.',
    category: 'messages',
    type: 'info',
    read: false,
    createdAt: '2026-07-14T16:20:00Z',
  },
  {
    id: 'NOT-007',
    title: 'Booking Rescheduled',
    message: 'Your Kitchen Plumbing Fix appointment has been rescheduled to 20 Jul 2026 at 11:00 AM.',
    category: 'bookings',
    type: 'warning',
    read: true,
    createdAt: '2026-07-14T09:15:00Z',
  },
  {
    id: 'NOT-008',
    title: 'Referral Bonus Credited',
    message: 'You earned ₹200 referral bonus! Your friend used your code to book their first service.',
    category: 'payments',
    type: 'success',
    read: false,
    createdAt: '2026-07-13T11:30:00Z',
  },
  {
    id: 'NOT-009',
    title: 'Weekend Sale Alert',
    message: 'Flat 30% off on all Painting services this weekend. Transform your home with ColorCoat Pro.',
    category: 'offers',
    type: 'promo',
    read: true,
    createdAt: '2026-07-13T08:00:00Z',
  },
  {
    id: 'NOT-010',
    title: 'Service Completed',
    message: 'Your Bathroom Deep Clean service has been completed. Rate your experience now!',
    category: 'bookings',
    type: 'success',
    read: true,
    createdAt: '2026-07-12T15:00:00Z',
  },
  {
    id: 'NOT-011',
    title: 'Payment Reminder',
    message: 'You have an unpaid invoice of ₹549 for Kitchen Plumbing Fix. Pay now to avoid cancellation.',
    category: 'payments',
    type: 'warning',
    read: false,
    createdAt: '2026-07-12T10:00:00Z',
  },
  {
    id: 'NOT-012',
    title: 'Maintenance Update',
    message: 'We will be performing scheduled maintenance on 18 Jul from 2 AM to 4 AM. Some features may be unavailable.',
    category: 'system',
    type: 'info',
    read: true,
    createdAt: '2026-07-11T18:00:00Z',
  },
  {
    id: 'NOT-013',
    title: 'Provider Responded',
    message: 'FixIt Plumbing Co. has accepted your query and will get back to you shortly.',
    category: 'messages',
    type: 'info',
    read: true,
    createdAt: '2026-07-11T14:15:00Z',
  },
  {
    id: 'NOT-014',
    title: 'Diwali Special Discount',
    message: 'Celebrate Diwali with up to 40% off on Home Cleaning, Painting, and Electrical services!',
    category: 'offers',
    type: 'promo',
    read: false,
    createdAt: '2026-07-10T07:00:00Z',
  },
  {
    id: 'NOT-015',
    title: 'Booking Cancelled',
    message: 'Your Interior Wall Painting booking has been cancelled as requested. Refund will be processed within 3-5 business days.',
    category: 'bookings',
    type: 'error',
    read: true,
    createdAt: '2026-07-09T16:45:00Z',
  },
  {
    id: 'NOT-016',
    title: 'New Services Added',
    message: 'We have added Smart Home Installation and Water Purifier Service to our catalogue. Check them out!',
    category: 'system',
    type: 'info',
    read: false,
    createdAt: '2026-07-09T09:00:00Z',
  },
  {
    id: 'NOT-017',
    title: 'Rating Request',
    message: 'You haven\'t rated your last 3 services. Share your feedback to help us improve!',
    category: 'system',
    type: 'info',
    read: true,
    createdAt: '2026-07-08T12:00:00Z',
  },
  {
    id: 'NOT-018',
    title: 'Cashback Offer Expiring',
    message: 'Your ₹100 cashback from the previous booking is expiring in 2 days. Book now to use it!',
    category: 'offers',
    type: 'warning',
    read: false,
    createdAt: '2026-07-08T08:30:00Z',
  },
  {
    id: 'NOT-019',
    title: 'Message from Support',
    message: 'Your query regarding invoice BKG-004 has been resolved. Check your email for details.',
    category: 'messages',
    type: 'success',
    read: true,
    createdAt: '2026-07-07T15:00:00Z',
  },
  {
    id: 'NOT-020',
    title: 'Account Security Alert',
    message: 'A new login was detected from Mumbai, India. If this wasn\'t you, please reset your password immediately.',
    category: 'system',
    type: 'error',
    read: true,
    createdAt: '2026-07-06T22:15:00Z',
  },
]

export default NOTIFICATIONS_DATA
