const BOOKINGS_DATA = [
  {
    id: 'BKG-001',
    serviceName: 'Full Home Deep Cleaning',
    serviceImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
    providerName: 'Sparkle Clean Pro',
    category: 'Home Cleaning',
    bookingDate: '18 Jul 2026',
    timeSlot: '10:00 AM - 1:00 PM',
    location: 'Mumbai, Maharashtra',
    price: 2499,
    status: 'confirmed',
    paymentStatus: 'paid',
    createdAt: '2026-07-10',
    timeline: [
      { status: 'booked', date: '10 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '10 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: null, label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-002',
    serviceName: 'AC Repair & Service',
    serviceImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=250&fit=crop',
    providerName: 'CoolAir Experts',
    category: 'AC Repair',
    bookingDate: '20 Jul 2026',
    timeSlot: '2:00 PM - 4:00 PM',
    location: 'Delhi, NCR',
    price: 399,
    status: 'pending',
    paymentStatus: 'unpaid',
    createdAt: '2026-07-12',
    timeline: [
      { status: 'booked', date: '12 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: null, label: 'Booking Confirmed' },
      { status: 'in_progress', date: null, label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-003',
    serviceName: 'Bathroom Deep Clean',
    serviceImage: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=250&fit=crop',
    providerName: 'CleanHome Services',
    category: 'Home Cleaning',
    bookingDate: '15 Jul 2026',
    timeSlot: '9:00 AM - 11:00 AM',
    location: 'Bangalore, Karnataka',
    price: 799,
    status: 'in_progress',
    paymentStatus: 'paid',
    createdAt: '2026-07-08',
    timeline: [
      { status: 'booked', date: '08 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '08 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '15 Jul 2026', label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-004',
    serviceName: 'Kitchen Plumbing Fix',
    serviceImage: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=250&fit=crop',
    providerName: 'FixIt Plumbing Co.',
    category: 'Plumbing',
    bookingDate: '10 Jul 2026',
    timeSlot: '11:00 AM - 12:30 PM',
    location: 'Mumbai, Maharashtra',
    price: 549,
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: '2026-07-05',
    timeline: [
      { status: 'booked', date: '05 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '05 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '09 Jul 2026', label: 'Provider Assigned' },
      { status: 'completed', date: '10 Jul 2026', label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-005',
    serviceName: 'Interior Wall Painting',
    serviceImage: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&h=250&fit=crop',
    providerName: 'ColorCoat Pro',
    category: 'Painting',
    bookingDate: '05 Jul 2026',
    timeSlot: '8:00 AM - 5:00 PM',
    location: 'Hyderabad, Telangana',
    price: 8999,
    status: 'cancelled',
    paymentStatus: 'refunded',
    createdAt: '2026-06-28',
    timeline: [
      { status: 'booked', date: '28 Jun 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '28 Jun 2026', label: 'Booking Confirmed' },
      { status: 'cancelled', date: '03 Jul 2026', label: 'Booking Cancelled' },
    ],
  },
  {
    id: 'BKG-006',
    serviceName: 'Electrical Wiring Repair',
    serviceImage: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=250&fit=crop',
    providerName: 'Shakti Electricals',
    category: 'Electrical',
    bookingDate: '08 Jul 2026',
    timeSlot: '3:00 PM - 5:00 PM',
    location: 'Chennai, Tamil Nadu',
    price: 349,
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: '2026-07-02',
    timeline: [
      { status: 'booked', date: '02 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '02 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '07 Jul 2026', label: 'Provider Assigned' },
      { status: 'completed', date: '08 Jul 2026', label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-007',
    serviceName: 'Home Moving & Packing',
    serviceImage: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=400&h=250&fit=crop',
    providerName: 'SmoothMove Packers',
    category: 'Moving',
    bookingDate: '25 Jul 2026',
    timeSlot: '7:00 AM - 6:00 PM',
    location: 'Pune, Maharashtra',
    price: 12999,
    status: 'pending',
    paymentStatus: 'unpaid',
    createdAt: '2026-07-15',
    timeline: [
      { status: 'booked', date: '15 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: null, label: 'Booking Confirmed' },
      { status: 'in_progress', date: null, label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-008',
    serviceName: 'Facial & Spa Treatment',
    serviceImage: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=400&h=250&fit=crop',
    providerName: 'Glow & Grace Spa',
    category: 'Beauty & Spa',
    bookingDate: '12 Jul 2026',
    timeSlot: '4:00 PM - 5:30 PM',
    location: 'Delhi, NCR',
    price: 999,
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: '2026-07-09',
    timeline: [
      { status: 'booked', date: '09 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '09 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '11 Jul 2026', label: 'Provider Assigned' },
      { status: 'completed', date: '12 Jul 2026', label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-009',
    serviceName: 'Office Deep Cleaning',
    serviceImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
    providerName: 'Sparkle Clean Pro',
    category: 'Home Cleaning',
    bookingDate: '22 Jul 2026',
    timeSlot: '9:00 AM - 2:00 PM',
    location: 'Bangalore, Karnataka',
    price: 4999,
    status: 'confirmed',
    paymentStatus: 'paid',
    createdAt: '2026-07-14',
    timeline: [
      { status: 'booked', date: '14 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '14 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: null, label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-010',
    serviceName: 'Smart Light Installation',
    serviceImage: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=250&fit=crop',
    providerName: 'Shakti Electricals',
    category: 'Electrical',
    bookingDate: '28 Jun 2026',
    timeSlot: '10:00 AM - 12:00 PM',
    location: 'Jaipur, Rajasthan',
    price: 1499,
    status: 'completed',
    paymentStatus: 'paid',
    createdAt: '2026-06-22',
    timeline: [
      { status: 'booked', date: '22 Jun 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '22 Jun 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '27 Jun 2026', label: 'Provider Assigned' },
      { status: 'completed', date: '28 Jun 2026', label: 'Service Completed' },
    ],
  },
  {
    id: 'BKG-011',
    serviceName: 'Full Home Deep Cleaning',
    serviceImage: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
    providerName: 'EcoClean Solutions',
    category: 'Home Cleaning',
    bookingDate: '02 Jul 2026',
    timeSlot: '8:00 AM - 12:00 PM',
    location: 'Mumbai, Maharashtra',
    price: 3499,
    status: 'rejected',
    paymentStatus: 'refunded',
    createdAt: '2026-06-25',
    timeline: [
      { status: 'booked', date: '25 Jun 2026', label: 'Booking Placed' },
      { status: 'rejected', date: '28 Jun 2026', label: 'Booking Rejected' },
    ],
  },
  {
    id: 'BKG-012',
    serviceName: 'AC Gas Refill',
    serviceImage: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=250&fit=crop',
    providerName: 'CoolAir Experts',
    category: 'AC Repair',
    bookingDate: '16 Jul 2026',
    timeSlot: '1:00 PM - 2:00 PM',
    location: 'Delhi, NCR',
    price: 1599,
    status: 'in_progress',
    paymentStatus: 'paid',
    createdAt: '2026-07-13',
    timeline: [
      { status: 'booked', date: '13 Jul 2026', label: 'Booking Placed' },
      { status: 'confirmed', date: '13 Jul 2026', label: 'Booking Confirmed' },
      { status: 'in_progress', date: '16 Jul 2026', label: 'Provider Assigned' },
      { status: 'completed', date: null, label: 'Service Completed' },
    ],
  },
]

export default BOOKINGS_DATA
