const BOOKING_DETAILS_DATA = {
  'BKG-001': {
    booking: {
      id: 'BKG-001',
      status: 'confirmed',
      paymentStatus: 'paid',
      bookingDate: '18 Jul 2026',
      createdAt: '2026-07-10T10:30:00',
      scheduledDate: '18 Jul 2026',
      scheduledTime: '10:00 AM - 1:00 PM',
      duration: '3 hours',
    },
    service: {
      name: 'Full Home Deep Cleaning',
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
      category: 'Home Cleaning',
      description: 'Complete deep cleaning service covering all rooms including kitchen and bathrooms. Includes dusting, mopping, window cleaning, and appliance exterior cleaning.',
      packageName: 'Premium',
      packagePrice: 2499,
    },
    provider: {
      id: 'PROV-001',
      name: 'Sparkle Clean Pro',
      photo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=100&h=100&fit=crop',
      phone: '+91 98765 43210',
      email: 'sparkle@cleanpro.com',
      experience: '5 years',
      rating: 4.8,
      totalJobs: 1247,
      verified: true,
      emergencyContact: '+91 98765 43211',
    },
    address: {
      customerName: 'Rahul Sharma',
      phone: '+91 98765 43210',
      line1: '402, Sunshine Apartments',
      line2: 'MG Road, Andheri East',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400069',
      landmark: 'Near Andheri Station',
      coordinates: { lat: 19.1136, lng: 72.8697 },
    },
    payment: {
      servicePrice: 2499,
      additionalCharges: 0,
      discount: 300,
      couponCode: 'NEWHOME',
      taxes: 199.92,
      platformFee: 49,
      totalAmount: 2447.92,
      paymentMethod: 'Credit Card (HDFC ****4821)',
      paymentStatus: 'paid',
      paidOn: '10 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-001',
      transactionId: 'TXN7A3B2C1D',
      paymentDate: '10 Jul 2026',
      dueDate: '18 Jul 2026',
    },
    notes: {
      customerNotes: 'Please use eco-friendly cleaning products. Focus on kitchen and bathrooms.',
      providerNotes: 'Will arrive with a team of 3. All equipment will be sanitized.',
      specialInstructions: 'Parking available in basement. Please ring doorbell twice.',
    },
    timeline: [
      { status: 'booked', date: '10 Jul 2026', time: '10:30 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '10 Jul 2026', time: '11:15 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: null, time: null, label: 'Provider Assigned', description: 'A provider will be assigned shortly.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider will start the service at scheduled time.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-002': {
    booking: {
      id: 'BKG-002',
      status: 'pending',
      paymentStatus: 'unpaid',
      bookingDate: '20 Jul 2026',
      createdAt: '2026-07-12T14:00:00',
      scheduledDate: '20 Jul 2026',
      scheduledTime: '2:00 PM - 4:00 PM',
      duration: '2 hours',
    },
    service: {
      name: 'AC Repair & Service',
      image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=250&fit=crop',
      category: 'AC Repair',
      description: 'Comprehensive AC repair and maintenance service. Includes gas check, filter cleaning, and performance tuning for optimal cooling.',
      packageName: 'Standard',
      packagePrice: 399,
    },
    provider: {
      id: 'PROV-002',
      name: 'CoolAir Experts',
      photo: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=100&h=100&fit=crop',
      phone: '+91 98765 43220',
      email: 'service@coolairexperts.com',
      experience: '8 years',
      rating: 4.6,
      totalJobs: 892,
      verified: true,
      emergencyContact: '+91 98765 43221',
    },
    address: {
      customerName: 'Priya Patel',
      phone: '+91 98765 43220',
      line1: '15, Green Valley Apartments',
      line2: 'Sector 62, Noida',
      city: 'Delhi',
      state: 'NCR',
      pincode: '201301',
      landmark: 'Near City Centre Mall',
      coordinates: { lat: 28.6294, lng: 77.3135 },
    },
    payment: {
      servicePrice: 399,
      additionalCharges: 0,
      discount: 0,
      couponCode: null,
      taxes: 31.92,
      platformFee: 29,
      totalAmount: 459.92,
      paymentMethod: null,
      paymentStatus: 'unpaid',
      paidOn: null,
    },
    invoice: {
      invoiceNumber: null,
      transactionId: null,
      paymentDate: null,
      dueDate: '20 Jul 2026',
    },
    notes: {
      customerNotes: 'AC is not cooling properly. Please check the gas level.',
      providerNotes: '',
      specialInstructions: 'Call before arriving. Gate code is #4521.',
    },
    timeline: [
      { status: 'booked', date: '12 Jul 2026', time: '2:00 PM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: null, time: null, label: 'Booking Confirmed', description: 'Awaiting provider confirmation.' },
      { status: 'provider_assigned', date: null, time: null, label: 'Provider Assigned', description: 'Provider will be assigned after confirmation.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider will start the service at scheduled time.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-003': {
    booking: {
      id: 'BKG-003',
      status: 'in_progress',
      paymentStatus: 'paid',
      bookingDate: '15 Jul 2026',
      createdAt: '2026-07-08T09:00:00',
      scheduledDate: '15 Jul 2026',
      scheduledTime: '9:00 AM - 11:00 AM',
      duration: '2 hours',
    },
    service: {
      name: 'Bathroom Deep Clean',
      image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=250&fit=crop',
      category: 'Home Cleaning',
      description: 'Thorough bathroom deep cleaning including tiles, grout, fixtures, mirrors, and complete sanitization.',
      packageName: 'Premium',
      packagePrice: 799,
    },
    provider: {
      id: 'PROV-003',
      name: 'CleanHome Services',
      photo: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=100&h=100&fit=crop',
      phone: '+91 98765 43230',
      email: 'book@cleanhome.in',
      experience: '4 years',
      rating: 4.5,
      totalJobs: 567,
      verified: true,
      emergencyContact: '+91 98765 43231',
    },
    address: {
      customerName: 'Arun Kumar',
      phone: '+91 98765 43230',
      line1: '88, Lake View Villa',
      line2: 'Whitefield',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560066',
      landmark: 'Opposite Lake View Park',
      coordinates: { lat: 12.9716, lng: 77.5946 },
    },
    payment: {
      servicePrice: 799,
      additionalCharges: 0,
      discount: 50,
      couponCode: 'CLEAN10',
      taxes: 63.92,
      platformFee: 29,
      totalAmount: 841.92,
      paymentMethod: 'UPI (Google Pay)',
      paymentStatus: 'paid',
      paidOn: '08 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-003',
      transactionId: 'TXN9D4E5F6G',
      paymentDate: '08 Jul 2026',
      dueDate: '15 Jul 2026',
    },
    notes: {
      customerNotes: 'Please focus on removing mold from ceiling corners.',
      providerNotes: 'Will bring specialized cleaning equipment.',
      specialInstructions: 'Please use the service entrance at the back.',
    },
    timeline: [
      { status: 'booked', date: '08 Jul 2026', time: '09:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '08 Jul 2026', time: '10:30 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '15 Jul 2026', time: '08:00 AM', label: 'Provider Assigned', description: 'CleanHome Services has been assigned.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider is on their way.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-004': {
    booking: {
      id: 'BKG-004',
      status: 'completed',
      paymentStatus: 'paid',
      bookingDate: '10 Jul 2026',
      createdAt: '2026-07-05T11:00:00',
      scheduledDate: '10 Jul 2026',
      scheduledTime: '11:00 AM - 12:30 PM',
      duration: '1.5 hours',
    },
    service: {
      name: 'Kitchen Plumbing Fix',
      image: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=250&fit=crop',
      category: 'Plumbing',
      description: 'Expert plumbing repair for kitchen sinks, pipes, and fixtures. Includes leak detection and repair.',
      packageName: 'Standard',
      packagePrice: 549,
    },
    provider: {
      id: 'PROV-004',
      name: 'FixIt Plumbing Co.',
      photo: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=100&h=100&fit=crop',
      phone: '+91 98765 43240',
      email: 'fixit@plumbing.com',
      experience: '12 years',
      rating: 4.9,
      totalJobs: 2103,
      verified: true,
      emergencyContact: '+91 98765 43241',
    },
    address: {
      customerName: 'Neha Singh',
      phone: '+91 98765 43240',
      line1: '7, Hill Top Residency',
      line2: 'Bandra West',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400050',
      landmark: 'Near Hill Top School',
      coordinates: { lat: 19.0596, lng: 72.8295 },
    },
    payment: {
      servicePrice: 549,
      additionalCharges: 150,
      discount: 0,
      couponCode: null,
      taxes: 55.92,
      platformFee: 29,
      totalAmount: 783.92,
      paymentMethod: 'Debit Card (SBI ****7890)',
      paymentStatus: 'paid',
      paidOn: '10 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-004',
      transactionId: 'TXN2H3I4J5K',
      paymentDate: '10 Jul 2026',
      dueDate: '10 Jul 2026',
    },
    notes: {
      customerNotes: 'The kitchen sink pipe is leaking. Also check the faucet.',
      providerNotes: 'Replaced pipe joint. Faucet washer replaced.',
      specialInstructions: '',
    },
    timeline: [
      { status: 'booked', date: '05 Jul 2026', time: '11:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '05 Jul 2026', time: '11:30 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '09 Jul 2026', time: '10:00 AM', label: 'Provider Assigned', description: 'FixIt Plumbing Co. has been assigned.' },
      { status: 'provider_started', date: '10 Jul 2026', time: '11:00 AM', label: 'Provider Started', description: 'Provider has started the service.' },
      { status: 'completed', date: '10 Jul 2026', time: '12:30 PM', label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-005': {
    booking: {
      id: 'BKG-005',
      status: 'cancelled',
      paymentStatus: 'refunded',
      bookingDate: '05 Jul 2026',
      createdAt: '2026-06-28T08:00:00',
      scheduledDate: '05 Jul 2026',
      scheduledTime: '8:00 AM - 5:00 PM',
      duration: '9 hours',
    },
    service: {
      name: 'Interior Wall Painting',
      image: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&h=250&fit=crop',
      category: 'Painting',
      description: 'Professional interior wall painting with premium paints. Includes surface preparation, priming, and two coats of paint.',
      packageName: 'Premium',
      packagePrice: 8999,
    },
    provider: {
      id: 'PROV-005',
      name: 'ColorCoat Pro',
      photo: 'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=100&h=100&fit=crop',
      phone: '+91 98765 43250',
      email: 'info@colorcoatpro.com',
      experience: '10 years',
      rating: 4.7,
      totalJobs: 1834,
      verified: true,
      emergencyContact: '+91 98765 43251',
    },
    address: {
      customerName: 'Vikram Mehta',
      phone: '+91 98765 43250',
      line1: '202, Cyber Heights',
      line2: 'Hitech City',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      landmark: 'Near Cyber Towers',
      coordinates: { lat: 17.4483, lng: 78.3915 },
    },
    payment: {
      servicePrice: 8999,
      additionalCharges: 0,
      discount: 500,
      couponCode: 'PAINT20',
      taxes: 719.92,
      platformFee: 49,
      totalAmount: 9267.92,
      paymentMethod: 'Credit Card (ICICI ****3210)',
      paymentStatus: 'refunded',
      paidOn: '28 Jun 2026',
      refundedOn: '03 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-005',
      transactionId: 'TXN6L7M8N9O',
      paymentDate: '28 Jun 2026',
      dueDate: '05 Jul 2026',
    },
    notes: {
      customerNotes: 'Need the living room painted in light blue. Bedrooms in white.',
      providerNotes: 'Cancelled due to weather conditions.',
      specialInstructions: '',
    },
    timeline: [
      { status: 'booked', date: '28 Jun 2026', time: '08:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '28 Jun 2026', time: '10:00 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'cancelled', date: '03 Jul 2026', time: '04:00 PM', label: 'Booking Cancelled', description: 'Booking was cancelled. Refund initiated.' },
    ],
  },
  'BKG-006': {
    booking: {
      id: 'BKG-006',
      status: 'completed',
      paymentStatus: 'paid',
      bookingDate: '08 Jul 2026',
      createdAt: '2026-07-02T15:00:00',
      scheduledDate: '08 Jul 2026',
      scheduledTime: '3:00 PM - 5:00 PM',
      duration: '2 hours',
    },
    service: {
      name: 'Electrical Wiring Repair',
      image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=250&fit=crop',
      category: 'Electrical',
      description: 'Safe and reliable electrical repair service. Troubleshooting, wiring repair, switchboard replacement, and safety inspection.',
      packageName: 'Standard',
      packagePrice: 349,
    },
    provider: {
      id: 'PROV-006',
      name: 'Shakti Electricals',
      photo: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=100&h=100&fit=crop',
      phone: '+91 98765 43260',
      email: 'shakti@electricals.in',
      experience: '15 years',
      rating: 4.4,
      totalJobs: 3215,
      verified: true,
      emergencyContact: '+91 98765 43261',
    },
    address: {
      customerName: 'Lakshmi Devi',
      phone: '+91 98765 43260',
      line1: '12, Krishna Nagar',
      line2: 'T. Nagar',
      city: 'Chennai',
      state: 'Tamil Nadu',
      pincode: '600017',
      landmark: 'Near Krishna Temple',
      coordinates: { lat: 13.0400, lng: 80.2279 },
    },
    payment: {
      servicePrice: 349,
      additionalCharges: 0,
      discount: 0,
      couponCode: null,
      taxes: 27.92,
      platformFee: 29,
      totalAmount: 405.92,
      paymentMethod: 'Cash',
      paymentStatus: 'paid',
      paidOn: '08 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-006',
      transactionId: 'TXN0P1Q2R3S',
      paymentDate: '08 Jul 2026',
      dueDate: '08 Jul 2026',
    },
    notes: {
      customerNotes: 'The main switchboard is sparking. Please check urgently.',
      providerNotes: 'Replaced faulty wiring and installed new MCB.',
      specialInstructions: 'Parking available on street.',
    },
    timeline: [
      { status: 'booked', date: '02 Jul 2026', time: '03:00 PM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '02 Jul 2026', time: '04:00 PM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '07 Jul 2026', time: '02:00 PM', label: 'Provider Assigned', description: 'Shakti Electricals has been assigned.' },
      { status: 'provider_started', date: '08 Jul 2026', time: '03:00 PM', label: 'Provider Started', description: 'Provider has started the service.' },
      { status: 'completed', date: '08 Jul 2026', time: '05:00 PM', label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-007': {
    booking: {
      id: 'BKG-007',
      status: 'pending',
      paymentStatus: 'unpaid',
      bookingDate: '25 Jul 2026',
      createdAt: '2026-07-15T07:00:00',
      scheduledDate: '25 Jul 2026',
      scheduledTime: '7:00 AM - 6:00 PM',
      duration: '11 hours',
    },
    service: {
      name: 'Home Moving & Packing',
      image: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=400&h=250&fit=crop',
      category: 'Moving',
      description: 'Complete home moving and packing service. Includes packing materials, furniture disassembly, loading, transport, and unloading.',
      packageName: 'Premium',
      packagePrice: 12999,
    },
    provider: {
      id: 'PROV-007',
      name: 'SmoothMove Packers',
      photo: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=100&h=100&fit=crop',
      phone: '+91 98765 43270',
      email: 'hello@smoothmove.in',
      experience: '7 years',
      rating: 4.3,
      totalJobs: 745,
      verified: true,
      emergencyContact: '+91 98765 43271',
    },
    address: {
      customerName: 'Amit Verma',
      phone: '+91 98765 43270',
      line1: '45, Royal Palm Estate',
      line2: 'Koregaon Park',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      landmark: 'Near Royal Palm Gate',
      coordinates: { lat: 18.5362, lng: 73.8490 },
    },
    payment: {
      servicePrice: 12999,
      additionalCharges: 0,
      discount: 1000,
      couponCode: 'MOVE500',
      taxes: 1039.92,
      platformFee: 49,
      totalAmount: 13087.92,
      paymentMethod: null,
      paymentStatus: 'unpaid',
      paidOn: null,
    },
    invoice: {
      invoiceNumber: null,
      transactionId: null,
      paymentDate: null,
      dueDate: '25 Jul 2026',
    },
    notes: {
      customerNotes: 'Please handle fragile items with care. We have antique furniture.',
      providerNotes: '',
      specialInstructions: 'Building has a service elevator. Use the loading bay at the back.',
    },
    timeline: [
      { status: 'booked', date: '15 Jul 2026', time: '07:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: null, time: null, label: 'Booking Confirmed', description: 'Awaiting provider confirmation.' },
      { status: 'provider_assigned', date: null, time: null, label: 'Provider Assigned', description: 'Provider will be assigned after confirmation.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider will start the service at scheduled time.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-008': {
    booking: {
      id: 'BKG-008',
      status: 'completed',
      paymentStatus: 'paid',
      bookingDate: '12 Jul 2026',
      createdAt: '2026-07-09T16:00:00',
      scheduledDate: '12 Jul 2026',
      scheduledTime: '4:00 PM - 5:30 PM',
      duration: '1.5 hours',
    },
    service: {
      name: 'Facial & Spa Treatment',
      image: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=400&h=250&fit=crop',
      category: 'Beauty & Spa',
      description: 'Luxurious facial and spa treatment using organic products. Includes deep cleansing, exfoliation, massage, and face mask.',
      packageName: 'Gold',
      packagePrice: 999,
    },
    provider: {
      id: 'PROV-008',
      name: 'Glow & Grace Spa',
      photo: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=100&h=100&fit=crop',
      phone: '+91 98765 43280',
      email: 'glow@grace.in',
      experience: '6 years',
      rating: 4.9,
      totalJobs: 1456,
      verified: true,
      emergencyContact: '+91 98765 43281',
    },
    address: {
      customerName: 'Sana Khan',
      phone: '+91 98765 43280',
      line1: '301, Rose Garden Apartments',
      line2: 'Saket',
      city: 'Delhi',
      state: 'NCR',
      pincode: '110017',
      landmark: 'Near Saket Metro Station',
      coordinates: { lat: 28.5289, lng: 77.2167 },
    },
    payment: {
      servicePrice: 999,
      additionalCharges: 0,
      discount: 100,
      couponCode: 'GLOW15',
      taxes: 79.92,
      platformFee: 29,
      totalAmount: 1007.92,
      paymentMethod: 'UPI (PhonePe)',
      paymentStatus: 'paid',
      paidOn: '12 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-008',
      transactionId: 'TXN4T5U6V7W',
      paymentDate: '12 Jul 2026',
      dueDate: '12 Jul 2026',
    },
    notes: {
      customerNotes: 'I have sensitive skin. Please use hypoallergenic products.',
      providerNotes: 'Used organic products suitable for sensitive skin.',
      specialInstructions: '',
    },
    timeline: [
      { status: 'booked', date: '09 Jul 2026', time: '04:00 PM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '09 Jul 2026', time: '05:00 PM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '11 Jul 2026', time: '03:00 PM', label: 'Provider Assigned', description: 'Glow & Grace Spa has been assigned.' },
      { status: 'provider_started', date: '12 Jul 2026', time: '04:00 PM', label: 'Provider Started', description: 'Provider has started the service.' },
      { status: 'completed', date: '12 Jul 2026', time: '05:30 PM', label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-009': {
    booking: {
      id: 'BKG-009',
      status: 'confirmed',
      paymentStatus: 'paid',
      bookingDate: '22 Jul 2026',
      createdAt: '2026-07-14T09:00:00',
      scheduledDate: '22 Jul 2026',
      scheduledTime: '9:00 AM - 2:00 PM',
      duration: '5 hours',
    },
    service: {
      name: 'Office Deep Cleaning',
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
      category: 'Home Cleaning',
      description: 'Professional office deep cleaning service. Includes workstations, floors, windows, pantry, and restroom sanitization.',
      packageName: 'Premium',
      packagePrice: 4999,
    },
    provider: {
      id: 'PROV-001',
      name: 'Sparkle Clean Pro',
      photo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=100&h=100&fit=crop',
      phone: '+91 98765 43210',
      email: 'sparkle@cleanpro.com',
      experience: '5 years',
      rating: 4.8,
      totalJobs: 1247,
      verified: true,
      emergencyContact: '+91 98765 43211',
    },
    address: {
      customerName: 'TechCorp Solutions',
      phone: '+91 98765 43290',
      line1: '5th Floor, Tech Park',
      line2: 'Electronic City',
      city: 'Bangalore',
      state: 'Karnataka',
      pincode: '560100',
      landmark: 'Near Electronic City Metro',
      coordinates: { lat: 12.8456, lng: 77.6605 },
    },
    payment: {
      servicePrice: 4999,
      additionalCharges: 500,
      discount: 500,
      couponCode: 'CORP20',
      taxes: 399.92,
      platformFee: 49,
      totalAmount: 5447.92,
      paymentMethod: 'Credit Card (Amex ****9001)',
      paymentStatus: 'paid',
      paidOn: '14 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-009',
      transactionId: 'TXN8X9Y0Z1A',
      paymentDate: '14 Jul 2026',
      dueDate: '22 Jul 2026',
    },
    notes: {
      customerNotes: 'Please clean after office hours. Coordinate with the building security.',
      providerNotes: 'Will arrive with a team of 5. After-hours cleaning confirmed.',
      specialInstructions: 'Security desk has the access card. Please show ID at reception.',
    },
    timeline: [
      { status: 'booked', date: '14 Jul 2026', time: '09:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '14 Jul 2026', time: '11:00 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: null, time: null, label: 'Provider Assigned', description: 'A provider will be assigned shortly.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider will start the service at scheduled time.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-010': {
    booking: {
      id: 'BKG-010',
      status: 'completed',
      paymentStatus: 'paid',
      bookingDate: '28 Jun 2026',
      createdAt: '2026-06-22T10:00:00',
      scheduledDate: '28 Jun 2026',
      scheduledTime: '10:00 AM - 12:00 PM',
      duration: '2 hours',
    },
    service: {
      name: 'Smart Light Installation',
      image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=400&h=250&fit=crop',
      category: 'Electrical',
      description: 'Professional smart lighting installation with WiFi setup. Includes dimmers, motion sensors, and voice control integration.',
      packageName: 'Standard',
      packagePrice: 1499,
    },
    provider: {
      id: 'PROV-006',
      name: 'Shakti Electricals',
      photo: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=100&h=100&fit=crop',
      phone: '+91 98765 43260',
      email: 'shakti@electricals.in',
      experience: '15 years',
      rating: 4.4,
      totalJobs: 3215,
      verified: true,
      emergencyContact: '+91 98765 43261',
    },
    address: {
      customerName: 'Deepak Joshi',
      phone: '+91 98765 43260',
      line1: '16, Pratap Nagar',
      line2: 'Sanganer',
      city: 'Jaipur',
      state: 'Rajasthan',
      pincode: '302029',
      landmark: 'Near Sanganer Airport Road',
      coordinates: { lat: 26.7873, lng: 75.8065 },
    },
    payment: {
      servicePrice: 1499,
      additionalCharges: 200,
      discount: 100,
      couponCode: 'SMART10',
      taxes: 119.92,
      platformFee: 29,
      totalAmount: 1747.92,
      paymentMethod: 'Net Banking (HDFC)',
      paymentStatus: 'paid',
      paidOn: '28 Jun 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-010',
      transactionId: 'TXN2B3C4D5E',
      paymentDate: '28 Jun 2026',
      dueDate: '28 Jun 2026',
    },
    notes: {
      customerNotes: 'Please install all 5 smart bulbs and the motion sensor.',
      providerNotes: 'All smart lights installed and connected to WiFi. Alexa integration done.',
      specialInstructions: 'Gate code is #7890. Dog in backyard.',
    },
    timeline: [
      { status: 'booked', date: '22 Jun 2026', time: '10:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '22 Jun 2026', time: '11:00 AM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '27 Jun 2026', time: '09:00 AM', label: 'Provider Assigned', description: 'Shakti Electricals has been assigned.' },
      { status: 'provider_started', date: '28 Jun 2026', time: '10:00 AM', label: 'Provider Started', description: 'Provider has started the service.' },
      { status: 'completed', date: '28 Jun 2026', time: '12:00 PM', label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
  'BKG-011': {
    booking: {
      id: 'BKG-011',
      status: 'rejected',
      paymentStatus: 'refunded',
      bookingDate: '02 Jul 2026',
      createdAt: '2026-06-25T08:00:00',
      scheduledDate: '02 Jul 2026',
      scheduledTime: '8:00 AM - 12:00 PM',
      duration: '4 hours',
    },
    service: {
      name: 'Full Home Deep Cleaning',
      image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=250&fit=crop',
      category: 'Home Cleaning',
      description: 'Complete deep cleaning service covering all rooms including kitchen and bathrooms.',
      packageName: 'Premium',
      packagePrice: 3499,
    },
    provider: {
      id: 'PROV-009',
      name: 'EcoClean Solutions',
      photo: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=100&h=100&fit=crop',
      phone: '+91 98765 43290',
      email: 'info@ecoclean.in',
      experience: '3 years',
      rating: 4.2,
      totalJobs: 345,
      verified: false,
      emergencyContact: '+91 98765 43291',
    },
    address: {
      customerName: 'Maya Desai',
      phone: '+91 98765 43290',
      line1: '55, Sea View Apartments',
      line2: 'Marine Drive',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400002',
      landmark: 'Near Marine Drive Chowpatty',
      coordinates: { lat: 18.9431, lng: 72.8230 },
    },
    payment: {
      servicePrice: 3499,
      additionalCharges: 0,
      discount: 300,
      couponCode: 'ECOCLEAN',
      taxes: 279.92,
      platformFee: 49,
      totalAmount: 3527.92,
      paymentMethod: 'Credit Card (Kotak ****6543)',
      paymentStatus: 'refunded',
      paidOn: '25 Jun 2026',
      refundedOn: '28 Jun 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-011',
      transactionId: 'TXN6F7G8H9I',
      paymentDate: '25 Jun 2026',
      dueDate: '02 Jul 2026',
    },
    notes: {
      customerNotes: '',
      providerNotes: 'Booking rejected due to scheduling conflict.',
      specialInstructions: '',
    },
    timeline: [
      { status: 'booked', date: '25 Jun 2026', time: '08:00 AM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'rejected', date: '28 Jun 2026', time: '02:00 PM', label: 'Booking Rejected', description: 'Provider was unable to accept this booking. Refund initiated.' },
    ],
  },
  'BKG-012': {
    booking: {
      id: 'BKG-012',
      status: 'in_progress',
      paymentStatus: 'paid',
      bookingDate: '16 Jul 2026',
      createdAt: '2026-07-13T13:00:00',
      scheduledDate: '16 Jul 2026',
      scheduledTime: '1:00 PM - 2:00 PM',
      duration: '1 hour',
    },
    service: {
      name: 'AC Gas Refill',
      image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&h=250&fit=crop',
      category: 'AC Repair',
      description: 'AC gas refill service for optimal cooling performance. Includes leak check and pressure testing.',
      packageName: 'Standard',
      packagePrice: 1599,
    },
    provider: {
      id: 'PROV-002',
      name: 'CoolAir Experts',
      photo: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=100&h=100&fit=crop',
      phone: '+91 98765 43220',
      email: 'service@coolairexperts.com',
      experience: '8 years',
      rating: 4.6,
      totalJobs: 892,
      verified: true,
      emergencyContact: '+91 98765 43221',
    },
    address: {
      customerName: 'Rohit Gupta',
      phone: '+91 98765 43220',
      line1: '78, Smart Homes',
      line2: 'Dwarka Sector 12',
      city: 'Delhi',
      state: 'NCR',
      pincode: '110078',
      landmark: 'Near Dwarka Sector 12 Metro',
      coordinates: { lat: 28.5921, lng: 77.0421 },
    },
    payment: {
      servicePrice: 1599,
      additionalCharges: 0,
      discount: 200,
      couponCode: 'COOL20',
      taxes: 127.92,
      platformFee: 29,
      totalAmount: 1555.92,
      paymentMethod: 'UPI (Paytm)',
      paymentStatus: 'paid',
      paidOn: '13 Jul 2026',
    },
    invoice: {
      invoiceNumber: 'INV-2026-012',
      transactionId: 'TXN1J2K3L4M',
      paymentDate: '13 Jul 2026',
      dueDate: '16 Jul 2026',
    },
    notes: {
      customerNotes: 'AC is not cooling at all. The gas might have leaked.',
      providerNotes: 'Carrying refrigerant gas and leak detection equipment.',
      specialInstructions: 'Please park in visitor parking. Call when you arrive.',
    },
    timeline: [
      { status: 'booked', date: '13 Jul 2026', time: '01:00 PM', label: 'Booking Placed', description: 'Your booking has been placed successfully.' },
      { status: 'confirmed', date: '13 Jul 2026', time: '02:00 PM', label: 'Booking Confirmed', description: 'Provider has confirmed your booking.' },
      { status: 'provider_assigned', date: '16 Jul 2026', time: '12:00 PM', label: 'Provider Assigned', description: 'CoolAir Experts has been assigned.' },
      { status: 'provider_started', date: null, time: null, label: 'Provider Started', description: 'Provider is on their way.' },
      { status: 'completed', date: null, time: null, label: 'Service Completed', description: 'Service completed successfully.' },
    ],
  },
}

function getBookingDetails(bookingId) {
  return BOOKING_DETAILS_DATA[bookingId] || null
}

export { getBookingDetails, BOOKING_DETAILS_DATA }
